services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI =${MONGODB_URI}
    volumes:
      - ./thumbnails:/thumbnails
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL= http://localhost:5000
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    depends_on:
      - backend